name: Publish documents
on: [push]

env:
  OUTPUT_FILENAME: "index"
  USER_AGENT: "$GITHUB_REPOSITORY ($GITHUB_SERVER_URL/$GITHUB_REPOSITORY)"

jobs:
  prepare-and-build-documents:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/smatts/markdown-slides-processor/main
    steps:
      - uses: actions/checkout@v3
      - run: |
          /build/process.sh
          ls -l
          mkdir .public
          cp -r * .public
          mv .public public
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
  upload:
    runs-on: ubuntu-latest
    steps:
    # Upload files
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull
        git status
        git add -f pdf/*
        git add -f webslides/*
        git add -f index.html
        git commit -m "Generate slides"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
