name: Publish documents
on: [push]

env:
  OUTPUT_FILENAME: "index"
  USER_AGENT: "$GITHUB_REPOSITORY ($GITHUB_SERVER_URL/$GITHUB_REPOSITORY)"

jobs:
  prepare-and-build-documents:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/smatts/markdown-slides-processor/main
    steps:
      - uses: actions/checkout@v3
      - run: |
          /build/process.sh
          cp index.html public
      - uses: actions/upload-artifact@master
        with:
          name: public
          path: public/
          
  upload-files:
    runs-on: ubuntu-latest
    needs: prepare-and-build-documents
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: public
          path: public/
      - name: Commit files
        run: |
          mkdir -p pdf
          cp public/*.pdf pdf/
          mkdir -p webslides
          cp public/*.html webslides/
          mkdir -p webslides/preview-images
          cp public/*.png webslides/preview-images
          cp public/index.html .
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git status
          git add -f pdf/*
          git add -f webslides/*
          git add -f index.html
          git commit -m "Generate slides"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
